version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
    ports:
      - 9200:9200
